### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'vector_size'

### ISSUE THREAD

**Issue by gianfilippo** [ddangelov/Top2Vec#102]
Hi,

I created a conda env with Python 3.6 and installed top2vec.

I then tried the example below to test the install

from top2vec import Top2Vec
from sklearn.datasets import fetch_20newsgroups
newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))
model = Top2Vec(documents=newsgroups.data, speed="learn", workers=8)

and I get the following output/error:
2020-12-18 00:20:24,861 - top2vec - INFO - Pre-processing documents for training
2020-12-18 00:20:31,459 - top2vec - INFO - Creating joint document/word embedding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "conda_envs/top2vec/lib/python3.6/site-packages/top2vec/Top2Vec.py", line 285, in __init__
    self.model = Doc2Vec(**doc2vec_args)
  File "/home/.local/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 634, in __init__
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'vector_size'

Can you please help me with it ?

Thanks

**Comment by ddangelov** [comment]
It looks like you might have an old version of gensim, try python 3.7 or 3.8 and the latest gensim.

**Comment by gianfilippo** [comment]
I has to use python 3.6, because when I use 3.7 or 3.8 I get the following error
ImportError: cannot import name 'logsumexp' from 'scipy.misc'
This is because 'logsumexp' is no longer in  'scipy.misc' but in 'scipy.special'
what do you suggest ?

**Comment by ddangelov** [comment]
I would suggest using python 3.7 or 3.8, creating a fresh environment and then `pip install top2vec`

**Comment by gianfilippo** [comment]
this is what I did  with python 3.7, 3.8 and eventually 3.6. The install is successful, but I get the 'logsumexp' runtime error.

**Comment by ddangelov** [comment]
Are you creating a new environment, like anaconda, with nothing else in it besides `top2vec`? You shouldn't be upgrading gensim, it should be a fresh install.

**Comment by gianfilippo** [comment]
I create a new env with miniconda, starting it only with python. top2vec is the only thing I am installing  in it
The fresh install does not install the latest gensim, as far as I can see

**Comment by ddangelov** [comment]
Are you using `pip install` or `conda install`?

**Comment by gianfilippo** [comment]
I am using pip install, following instructions
Also, I just did another install. 
I created a new env, overriding the old one. This time  did not specify the python version. 
I then installed (pip) top2vec and I get the 'vector_size' error as before (see below)

Slow version of gensim.models.doc2vec is being used
2020-12-21 21:55:53.783530: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-21 21:55:54,782 - top2vec - INFO - Pre-processing documents for training
2020-12-21 21:55:54,783 - top2vec - INFO - Creating joint document/word embedding
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    model = Top2Vec(documents)
  File "/home/.local/lib/python3.8/site-packages/top2vec/Top2Vec.py", line 285, in __init__
    self.model = Doc2Vec(**doc2vec_args)
  File "/home/.local/lib/python3.8/site-packages/gensim-3.1.0-py3.8-linux-x86_64.egg/gensim/models/doc2vec.py", line 631, in __init__
    super(Doc2Vec, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'vector_size'

**Comment by ddangelov** [comment]
I am sorry I can't help any further, this seems like a gensim/environment issue.

**Comment by gianfilippo** [comment]
ok. thanks anyway
