### ISSUE TITLE
Cached model file gets removed

### ISSUE THREAD

**Issue by arnov** [ddangelov/Top2Vec#115]
I keep running into the issue that my local Tensforflow hub model file gets removed, from what I think is a temp dir. I am not sure if it's the responsibility of the top2vec library, but it's annoying nonetheless. I use the `universal-sentence-encoder-multilingual` embedding model.

Stacktrace:

```
Traceback (most recent call last):
  File "src/model/extractor.py", line 64, in extract_from_text
    self.model.add_documents([text])
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/top2vec/Top2Vec.py", line 929, in add_documents
    document_vectors = self._embed_documents(docs_training)
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/top2vec/Top2Vec.py", line 386, in _embed_documents
    self._check_model_status()
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/top2vec/Top2Vec.py", line 649, in _check_model_status
    self.embed = hub.load(module)
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 114, in load
    obj = tf_v1.saved_model.load_v2(module_path, tags=tags)
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 614, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/Users/arnov/.pyenv/versions/transformers/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: /var/folders/z_/_x0b8wvn1531mdz6dxzv1rnsx9bm1d/T/tfhub_modules/26c892ffbc8d7b032f5a95f316e2841ed4f1608c/{saved_model.pbtxt|saved_model.pb}
```

The solution is to manually remove the folder and then Tensorflow hub will redownload the model. It's only annoying I always have to do this after a few days.

**Comment by ddangelov** [comment]
I agree, unfortunately it is a known tensorflow issue. One way to get around it is to download the model and pass the filepath to Top2Vec with `embedding_model_path`. When loading an already trained Top2Vec model you can change where to look for the `universal-sentence-encoder` with the `update_embedding_model_path` function.
