### ISSUE TITLE
Cannot use list of strings as an input to the model : TypeError: Cannot convert list to numpy.ndarray

### ISSUE THREAD

**Issue by vedpd** [ddangelov/Top2Vec#186]
Tried reading one of the datasets with a column consisting of text data. Obtained a list of strings using the textual column from the dataframe.

On running the model, it throws the error :  
**TypeError: Cannot convert list to numpy.ndarray**

**Operations done :** 

1. info_df = pd.read_csv('/content/info.csv')
2.  info_df. head
3.  input_str_lst = df.Reviews.tolist()
4. type(input_str_lst)     : O/P = List
5. model = Top2Vec(documents=input_str_lst)
![error_top2vec](https://user-images.githubusercontent.com/16535571/122648683-dc124480-d147-11eb-946b-85d8a43b2539.jpg)
![model_error_top2vec](https://user-images.githubusercontent.com/16535571/122648694-e3d1e900-d147-11eb-8d20-ccd342168e9d.jpg)

Attached are screenshots

**Comment by ddangelov** [comment]
Which version of top2vec and gensim do you have?

**Comment by will-jac** [comment]
I also have this issue with the default embedding model. You can use `embedding_model='universal-sentence-encoder'` to get around this, if it's appropriate for your use case.


`>>> top2vec.__version__
'1.0.26'
>>> gensim.__version__
'3.8.3'
>>> model = Top2Vec(['test' for _ in range(51)])
2021-07-29 11:49:30,517 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
2021-07-29 11:49:30,518 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
Exception in thread Thread-85:
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/site-packages/gensim/models/base_any2vec.py", line 210, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, job_parameters, thread_private_mem)
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/site-packages/gensim/models/doc2vec.py", line 463, in _do_train_job
    tally += train_document_dbow(
  File "gensim/models/doc2vec_inner.pyx", line 349, in gensim.models.doc2vec_inner.train_document_dbow
TypeError: Cannot convert list to numpy.ndarr`

**Comment by ddangelov** [comment]
I have tested this with the exact same `top2vec` and `gensim` versions and I cannot recreate it.
