### ISSUE TITLE
Top2Vec fails when a single topic is generated

### ISSUE THREAD

**Issue by will-jac** [ddangelov/Top2Vec#192]
I'm running Top2Vec in an automated fashion on several custom corpuses. For some, Top2Vec generates a single topic, which causes an error. For a reproducible example, run:

`Top2Vec(['test' for _ in range(51)], embedding_model='universal-sentence-encoder')`

The loop is required as Top2Vec requires >50 inputs.

Note that I consider this a bug as I still want to use Top2Vec to get the keywords from the topic, even if there is only one.

The stack trace produced is:
`2021-07-29 11:44:52,437 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
2021-07-29 11:44:52,440 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2021-07-29 11:44:56,486 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2021-07-29 11:44:56,666 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2021-07-29 11:44:58,501 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2021-07-29 11:44:58,502 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/site-packages/top2vec/Top2Vec.py", line 376, in __init__
    self._create_topic_vectors(cluster.labels_)
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/site-packages/top2vec/Top2Vec.py", line 589, in _create_topic_vectors
    np.vstack([self._get_document_vectors(norm=False)[np.where(cluster_labels == label)[0]]
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/jack/.pyenv/versions/3.9.5/lib/python3.9/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate`

**Comment by ddangelov** [comment]
This usually occurs when your corpus is too small. Try increasing corpus size and changing the value of `min_count=2`
