### ISSUE TITLE
Top2Vec installation issue: name 'ExitStack' is not defined

### ISSUE THREAD

**Issue by nathanisimov** [ddangelov/Top2Vec#211]
Hello!
Trying to import top2vec, but get that issue:

from top2vec import Top2Vec
Traceback (most recent call last):
  File "<ipython-input-224-9a81163f0da9>", line 1, in <module>
    from top2vec import Top2Vec
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/top2vec/__init__.py", line 1, in <module>
    from top2vec.Top2Vec import Top2Vec
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/top2vec/Top2Vec.py", line 10, in <module>
    import umap
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/umap/umap_.py", line 54, in <module>
    from umap.layouts import (
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/umap/layouts.py", line 36, in <module>
    "dim": numba.types.int32,
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/numba/core/decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "/Users/natananisimov/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 865, in compile
**NameError: name 'ExitStack' is not defined**

How can I solve it?
Thank you for your attention!

**Comment by ddangelov** [comment]
Looks like dependency issues, I would create a fresh conda environment and install there.
