### ISSUE TITLE
Can not download distiluse-base-multilingual-cased ?

### ISSUE THREAD

**Issue by khiemntu** [ddangelov/Top2Vec#227]
This is an issue

/home/khiemntu/demo_nlp/nlp/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
2021-12-11 00:14:42,249 - top2vec - INFO - Downloading distiluse-base-multilingual-cased model
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    model = Top2Vec(documents, embedding_model='distiluse-base-multilingual-cased', speed="deep-learn", workers=100, min_count=0)
  File "/home/khiemntu/demo_nlp/nlp/lib/python3.8/site-packages/top2vec/Top2Vec.py", line 334, in __init__
    self._check_model_status()
  File "/home/khiemntu/demo_nlp/nlp/lib/python3.8/site-packages/top2vec/Top2Vec.py", line 857, in _check_model_status
    model = SentenceTransformer(module)
  File "/home/khiemntu/demo_nlp/nlp/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    modules = self._load_sbert_model(model_path)
  File "/home/khiemntu/demo_nlp/nlp/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 824, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/home/khiemntu/demo_nlp/nlp/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py", line 122, in load
    config = json.load(fIn)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Anyone know the root cause of issue above when I use `model = Top2Vec(documents, embedding_model='distiluse-base-multilingual-cased', speed="deep-learn", workers=100, min_count=0)` ? Thanks for your help!

**Comment by ddangelov** [comment]
I will look into this.

**Comment by ddangelov** [comment]
It looks like a naming convention change, it should be fixed in the next version. In the meantime I would recommend using `embedding_model='universal-sentence-encoder-multilingual'`.

**Comment by ddangelov** [comment]
After a closer look you shouldn't be getting this error. What version of `top2vec` and `sentence-transformers` do you have?
