### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec ... If using use_corpus_file = True

### ISSUE THREAD

**Issue by p-dre** [ddangelov/Top2Vec#244]
If I using use_corpus_file = True in combination with chracters like ł or ę at the documents, I get a UnicodeEncodeError: at temp.write(lines). With use_corpus_file = False the model works well. The encoding of the data is 'utf-8'. 

```
 2022-03-02 17:41:11,591 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Temp/ipykernel_5868/1583447774.py", line 1, in <module>
    model = Top2Vec (list(tweets['text']),
  File "C:\Users\\anaconda3\envs\python_38\lib\site-packages\top2vec\Top2Vec.py", line 292, in __init__
    temp.write(lines)
  File "C:\Users\\anaconda3\envs\python_38\lib\tempfile.py", line 473, in func_wrapper
    return func(*args, **kwargs)
  File "C:\Users\\anaconda3\envs\python_38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37036-37045: character maps to <undefined>
```

**Comment by ddangelov** [comment]
I would use the `corpus_file=False` in that scenario, the performance shouldn't be substantially worse.
