### ISSUE TITLE
numpy.core._exceptions._ArrayMemoryError

### ISSUE THREAD

**Issue by satrio-yudhoatmojo** [ddangelov/Top2Vec#296]
Hi, I'm running Top2Vec on 1,042,340 data.  Here's the parameters I used:

`model = Top2Vec(documents=documents,
				min_count=4,
				ngram_vocab=True, # add phrases to topic descriptions
				embedding_model='doc2vec', # use doc2vec for creating the document embedding
				split_documents=True, # enable the split_documents because we have large dataset
				speed='learn', # this is chosen instead of deep-learn due to the size of our dataset
				document_ids=document_ids, # list of IDs
				workers= mp.cpu_count(),
				verbose=True
				)`

During the **Finding Topic** task, it raised the following error:

`Traceback (most recent call last):
  File "C:\Users\***\Documents\Research\***\***\Top2Vec\Top2Vec_topic_model.py", line 44, in <module>
    model = Top2Vec(documents=documents,
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\top2vec\Top2Vec.py", line 690, in __init__
    self.topic_words, self.topic_word_scores = self._find_topic_words_and_scores(topic_vectors=self.topic_vectors)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\top2vec\Top2Vec.py", line 979, in _find_topic_words_and_scores
    top_scores = np.flip(np.sort(res, axis=1), axis=1)
  File "<__array_function__ internals>", line 180, in sort
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py", line 1003, in sort
    a = asanyarray(a).copy(order="K")
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 6.78 GiB for an array with shape (10503, 173401) and data type float32`

Any suggestion how to fix/avoid this error?

**Comment by ddangelov** [comment]
Looks like you are short on RAM. I would either run on a machine with more RAM or train Top2Vec model on smaller random subset of your data then  use `add_documents` on the remainder of the data.
