### ISSUE TITLE
Error installing top2vec[sentence_encoders]

### ISSUE THREAD

**Issue by Sayum24** [ddangelov/Top2Vec#355]
I tried installing top2vec[sentence_encoders] by this command:
```
pip install 'top2vec[sentence_encoders]'  
```
I got the following output
```
Requirement already satisfied: top2vec[sentence_encoders] in ./.venv/lib/python3.10/site-packages (1.0.34)
WARNING: top2vec 1.0.34 does not provide the extra 'sentence-encoders'
Requirement already satisfied: numpy>=1.20.0 in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (1.26.3)
Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (2.1.4)
Requirement already satisfied: scikit-learn>=1.2.0 in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (1.4.0)
Requirement already satisfied: gensim>=4.0.0 in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (4.3.2)
Requirement already satisfied: umap-learn>=0.5.1 in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (0.5.5)
Requirement already satisfied: hdbscan>=0.8.27 in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (0.8.33)
Requirement already satisfied: wordcloud in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (1.9.3)
Requirement already satisfied: tensorflow in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (2.15.0)
Requirement already satisfied: tensorflow-hub in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (0.16.1)
INFO: pip is looking at multiple versions of top2vec[sentence-encoders] to determine which version is compatible with other requirements. This could take a while.
Collecting top2vec[sentence_encoders]
  Using cached top2vec-1.0.33-py3-none-any.whl.metadata (18 kB)
WARNING: top2vec 1.0.33 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.32-py3-none-any.whl.metadata (18 kB)
WARNING: top2vec 1.0.32 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.31-py3-none-any.whl.metadata (18 kB)
WARNING: top2vec 1.0.31 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.30-py3-none-any.whl.metadata (18 kB)
WARNING: top2vec 1.0.30 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.29-py3-none-any.whl (26 kB)
WARNING: top2vec 1.0.29 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.28-py3-none-any.whl (25 kB)
WARNING: top2vec 1.0.28 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.27-py3-none-any.whl (25 kB)
WARNING: top2vec 1.0.27 does not provide the extra 'sentence-encoders'
INFO: pip is still looking at multiple versions of top2vec[sentence-encoders] to determine which version is compatible with other requirements. This could take a while.
  Using cached top2vec-1.0.26-py3-none-any.whl (23 kB)
WARNING: top2vec 1.0.26 does not provide the extra 'sentence-encoders'
Collecting gensim<4.0.0 (from top2vec[sentence_encoders])
  Using cached gensim-3.8.3.tar.gz (23.4 MB)
  Preparing metadata (setup.py) ... done
Collecting top2vec[sentence_encoders]
  Using cached top2vec-1.0.25-py3-none-any.whl (23 kB)
WARNING: top2vec 1.0.25 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.24-py3-none-any.whl (22 kB)
WARNING: top2vec 1.0.24 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.23-py3-none-any.whl (22 kB)
WARNING: top2vec 1.0.23 does not provide the extra 'sentence-encoders'
  Using cached top2vec-1.0.22-py3-none-any.whl (22 kB)
WARNING: top2vec 1.0.22 does not provide the extra 'sentence-encoders'
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached top2vec-1.0.21-py3-none-any.whl (22 kB)
WARNING: top2vec 1.0.21 does not provide the extra 'sentence-encoders'
Requirement already satisfied: pynndescent>=0.4 in ./.venv/lib/python3.10/site-packages (from top2vec[sentence_encoders]) (0.5.11)
Collecting joblib<1.0.0 (from top2vec[sentence_encoders])
  Using cached joblib-0.17.0-py3-none-any.whl (301 kB)
Collecting numpy (from top2vec[sentence_encoders])
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-install-s2ywe1e3/numpy_78ee05df48024be18c30b9ced9f2717b/tools/cythonize.py", line 235, in <module>
          main()
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-install-s2ywe1e3/numpy_78ee05df48024be18c30b9ced9f2717b/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-install-s2ywe1e3/numpy_78ee05df48024be18c30b9ced9f2717b/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-install-s2ywe1e3/numpy_78ee05df48024be18c30b9ced9f2717b/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-install-s2ywe1e3/numpy_78ee05df48024be18c30b9ced9f2717b/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/samu/Documents/DHBW/6._Semester/Projekte_6._Semester/KI_Projects/.venv/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/samu/Documents/DHBW/6._Semester/Projekte_6._Semester/KI_Projects/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/samu/Documents/DHBW/6._Semester/Projekte_6._Semester/KI_Projects/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/samu/Documents/DHBW/6._Semester/Projekte_6._Semester/KI_Projects/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-build-env-ub9lae5d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-build-env-ub9lae5d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/jg/_gq097v93c96v89nb7try5dr0000gn/T/pip-build-env-ub9lae5d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 499, in <module>
          setup_package()
        File "setup.py", line 479, in setup_package
          generate_cython()
        File "setup.py", line 274, in generate_cython
          raise RuntimeError("Running cythonize failed!")
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by Sayum24** [comment]
it seems it is already installed...

**Comment by Sayum24** [comment]
I was coding in a Jupyter-Notebook on my machine.

After uploading it on [colab.research.google.com](https://colab.research.google.com/) it worked.
