### ISSUE TITLE
Memoy error by finding topics

### ISSUE THREAD

**Issue by p-dre** [ddangelov/Top2Vec#75]
I get a memory error very late in the code. While finding the topics.  I had previously thought that the meomory critical part of the process was umap. I have 128GB available and a dataset with 3 million rows. Is there a way to further optimize the process. For example to delete an intermediate result within the code. Do you have an idea?

```
Top2vec_model= Top2Vec(documents_text, min_count = 3,
                       speed = "fast-learn", 
                       document_ids=document_ids, 
                       workers = workers_n,keep_documents=False)

2020-11-22 17:30:29,654 - top2vec - INFO - Pre-processing documents for training
2020-11-22 17:32:48,431 - top2vec - INFO - Creating joint document/word embedding
2020-11-22 22:51:28,030 - top2vec - INFO - Creating lower dimension embedding of documents
2020-11-22 23:12:07,766 - top2vec - INFO - Finding dense areas of documents
2020-11-22 23:47:03,066 - top2vec - INFO - Finding topics
Traceback (most recent call last):

  File "<ipython-input-4-de81fc2fe1d0>", line 4, in <module>
    workers = workers_n,keep_documents=False)

  File "C:\Users\anaconda\.conda\envs\top2vec_final\lib\site-packages\top2vec\Top2Vec.py", line 335, in __init__
    self.topic_words, self.topic_word_scores = self._find_topic_words_and_scores(topic_vectors=self.topic_vectors)

  File "C:\Users\anaconda\.conda\envs\top2vec_final\lib\site-packages\top2vec\Top2Vec.py", line 536, in _find_topic_words_and_scores
    top_scores = np.flip(np.sort(res, axis=1), axis=1)

  File "<__array_function__ internals>", line 6, in sort

  File "C:\Users\anaconda\.conda\envs\top2vec_final\lib\site-packages\numpy\core\fromnumeric.py", line 990, in sort
    a = asanyarray(a).copy(order="K")

MemoryError: Unable to allocate 16.7 GiB for an array with shape (21747, 206210) and data type float32
```

**Comment by ddangelov** [comment]
For a dataset with 3 million documents I would set `min_count` to a higher value, 50 to 100. It sounds like you are only short 16.7GiB, is the rest of your memory used up?

**Comment by p-dre** [comment]
Thanks, if I set the min_count to 4 or higher its works.
When I start top2vec my meomory usage is at 4 % and with min_count = 3 all my memory is used
