### ISSUE TITLE
Problem while installing Top2Vec

### ISSUE THREAD

**Issue by evangeliazve** [ddangelov/Top2Vec#80]
Hello team,

Thank you for this great solution for topic modeling and semantic search.

Since 2 weeks I'm facing issues using Top2Vec in Python. I have saved models and I have been tring to load them without success.

On the top of that today I tried to import Top2Vec but I get the following :

from top2vec import Top2Vec
Traceback (most recent call last):

  File "<ipython-input-13-9a81163f0da9>", line 1, in <module>
    from top2vec import Top2Vec

  File "C:\Users\evangelia.zve\Anaconda3\lib\site-packages\top2vec\__init__.py", line 1, in <module>
    from top2vec.Top2Vec import Top2Vec

  File "C:\Users\evangelia.zve\Anaconda3\lib\site-packages\top2vec\Top2Vec.py", line 23, in <module>
    import tensorflow_text

  File "C:\Users\evangelia.zve\Anaconda3\lib\site-packages\tensorflow_text\__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics

  File "C:\Users\evangelia.zve\Anaconda3\lib\site-packages\tensorflow_text\python\metrics\__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *

  File "C:\Users\evangelia.zve\Anaconda3\lib\site-packages\tensorflow_text\python\metrics\text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))

  File "C:\Users\evangelia.zve\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

NotFoundError: C:\Users\evangelia.zve\Anaconda3\lib\site-packages\tensorflow_text\python\metrics\_text_similarity_metric_ops.so not found

Where they any crucial chnages within your package? Does anyone else alerted you on the same issue?

Thank you in advance for your help and support.

Best Regards,
Evangelia Zve

**Comment by ddangelov** [comment]
This is due to a tensorflow requirement that was made optional in the latest version to prevent this error. Try `pip install top2vec==1.0.16`.

Alternately if you trained your model before the `embedding_model` parameter options existed try `pip install top2vec==1.0.11`. 

If neither solution works I would re-train the model with the latest version.

**Comment by evangeliazve** [comment]
Hello,

It seems to work. Thank you for your support.

If anything else occurs I'll let you know.

Best Regards,
