### ISSUE TITLE
Error importing top2vec - 'ModulePassManager' object has no attribute 'add_loop_rotate_pass'

### ISSUE THREAD

**Issue by baruchih** [ddangelov/Top2Vec#99]
Hello,

I have installed top2vec `1.0.19`

When trying to import using `from top2vec import Top2Vec`
I am getting the following error:

```
Traceback (most recent call last):
  File "top2vec_run.py", line 2, in <module>
    from top2vec import Top2Vec
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/top2vec/__init__.py", line 1, in <module>
    from top2vec.Top2Vec import Top2Vec
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/top2vec/Top2Vec.py", line 10, in <module>
    import umap
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/umap/umap_.py", line 27, in <module>
    import numba
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/__init__.py", line 212, in <module>
    import numba.typed
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/typed/__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/typed/typeddict.py", line 23, in <module>
    def _make_dict(keyty, valty):
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/decorators.py", line 260, in njit
    return jit(*args, **kws)
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/decorators.py", line 183, in jit
    return wrapper(pyfunc)
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/decorators.py", line 210, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/dispatcher.py", line 746, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/utils.py", line 277, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/base.py", line 259, in __init__
    self.init()
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/codegen.py", line 1086, in __init__
    self._init(self._llvm_module)
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/codegen.py", line 1105, in _init
    self._mpm_cheap = self._module_pass_manager(loop_vectorize=False,
  File "/home/baruchih/anaconda3/envs/orchestra/lib/python3.8/site-packages/numba/core/codegen.py", line 1147, in _module_pass_manager
    pm.add_loop_rotate_pass()
AttributeError: 'ModulePassManager' object has no attribute 'add_loop_rotate_pass'
```

Any ideas on what I am missing?
Thanks!

**Comment by flozi00** [comment]
you need to install the newest version of numba to make it work, that was to solution for my case

**Comment by baruchih** [comment]
Thanks!
Indeed it solved the issue
